# Auto-merge as documented in official Github docs
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions

name: Auto-review Dependabot PRs
on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot-reviewer:
    runs-on: ubuntu-latest

    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.5.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Approve and Enable auto-merge
        run: |
          gh pr merge --auto --squash "$PR_URL"
          gh pr review $PR_URL \
          --approve -b "**I'm approving** this pull request because it includes a patch or minor \
          update to dependencies that doesn't need any manual check
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


      # - name: Approve and auto-merge
      #   if: steps.check-whitelist.conclusion == 'success' && steps.check-whitelist.outputs.allInWhitelist == 'true'
      #   run: |
      #     gh pr merge --auto --squash "$PR_URL"
      #     gh pr review $PR_URL \
      #     --approve -b "**I'm approving** this pull request because it includes a patch or minor \
      #     update to dependencies that are already whitelisted.

      #     The reason this library is whitelisted is that ${{ steps.check-whitelist.outputs.reasons}}"
      #   env:
      #     PR_URL: ${{github.event.pull_request.html_url}}
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
