name: go-version

on: pull_request_target

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Get build image from Makefile
        id: build_image_step
        run: echo "build_image=mimir-build-image:felix-update-go-to-1.20.5-31cf42ae2" >> "$GITHUB_OUTPUT"
    outputs:
      build_image: ${{ steps.build_image_step.outputs.build_image }}
  
  compare-manifests:
    runs-on: ubuntu-latest
    needs:
      - prepare
    steps:
    - uses: actions/checkout@v3
    - name: Get Go Version
      uses: ${{ needs.prepare.outputs.build_image }}
      with:
        command: echo "go-version=$(go version)" >> "$GITHUB_OUTPUT" 
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ needs.go-version.outputs.go-version }}
    - name: Download Dependencies
      run: |
        go mod download
        go mod vendor